apiVersion: v1
kind: Service
metadata:
  name: developer-iq
spec:
  type: LoadBalancer
  ports:
    - port: 80
      targetPort: 8080
  selector:
    app: developer-iq
---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: developer-iq
spec:
  replicas: 2
  strategy:
    type: RollingUpdate
    rollingUpdate:
      maxUnavailable: 2
      maxSurge: 2
  selector:
    matchLabels:
      app: developer-iq
  template:
    metadata:
      labels:
        app: developer-iq
    spec:
      containers:
        - name: developer-iq
          image: CONTAINER_IMAGE
          securityContext:
            privileged: false
            readOnlyRootFilesystem: true
            allowPrivilegeEscalation: false
          ports:
            - containerPort: 8080